version: "3.0"
services:
  app:
    restart: always
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - common_data:/usr/local/lib/python3.8/site-packages/casbert/resources/sedmlImages
    env_file: .env
    command: bash -c "cd /usr/src && APP_SETTING=.env python -m app.server"
  
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/
    volumes_from:
      - app
    depends_on:
      - frontend
      - app

  frontend:
    restart: always
    build: ./frontend/
    depends_on:
      - app
  
      
volumes:
  common_data:

