version: "2.0"
services:
  app:
    restart: always
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - /usr/src/app/casbert_searcher/casbertSearcher/resources/sedmlImages
    env_file: .env
    command: bash -c "cd /usr/src && APP_SETTING=.env python -m app.server"
  
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/images
    volumes_from:
      - app
    depends_on:
      - frontend
      - app
    # links:
    #   - app:app

  frontend:
    restart: always
    build: ./frontend/
    depends_on:
      - app
